# Generated by Django 2.2 on 2020-01-04 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensores_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50)),
                ('actions', models.CharField(max_length=20)),
                ('message', models.CharField(max_length=120)),
                ('numero', models.DecimalField(decimal_places=4, max_digits=5)),
            ],
        ),
    ]
