# Generated by Django 3.0.1 on 2019-12-30 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sensores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120)),
                ('id_mcu', models.CharField(max_length=12)),
                ('nro_sensores', models.DecimalField(decimal_places=2, max_digits=5, max_length=3)),
                ('activo', models.BooleanField(default=False)),
                ('temperatura', models.DecimalField(decimal_places=5, max_digits=6)),
                ('ph', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
