# Generated by Django 3.0.1 on 2019-12-30 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_view', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensores',
            name='temperatura',
            field=models.DecimalField(decimal_places=2, max_digits=4),
        ),
    ]
