# Generated by Django 3.0.1 on 2019-12-31 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_view', '0002_auto_20191230_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensores',
            name='nro_piscina',
            field=models.DecimalField(decimal_places=0, default=True, max_digits=4),
            preserve_default=False,
        ),
    ]
